gameshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

shop/urls.py
from django.urls import path, include

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path("loguser", views.login_user, name="loguser"),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('signup', views.signup, name='signup'),
    path('home', views.home, name='home'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/error', views.payment_error, name='payment_error'),
    path('payment/cancel', views.payment_cancel, name='payment_cancel'),
    path('catalog', views.catalog_view, name='catalog'),
    path('games/<int:game_id>/info', views.game_info, name='game_info'),
    path('developer', views.developer_view, name='developer'),
    path('search', views.search, name='search'),
    path('games/<int:game_id>/play', views.play_game, name='play_game'),
    path('developer/publish', views.publish_page_view, name='publish'),
    path('developer/publish_game', views.create_game, name='publish_game'),
    path('developer/mygames', views.developer_games, name='developer_games'),
    path('developer/games/<int:game_id>/edit', views.edit_game, name='editgame'),
    path('developer/games/<int:game_id>/update', views.edit_game_update, name='updategame'),
    path('developer/games/<int:game_id>/delete', views.edit_game_delete, name='deletegame'),
    path('facebook', views.facebook_handler, name='facebook_handler'),


]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Player(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Developer(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE)

#Create your models here.
class Game(models.Model):
    title = models.CharField(max_length=30, null=False, blank=False, unique=False)
    price = models.FloatField(null=False, blank=False, unique=False)
    url = models.URLField(max_length=300, null=False, blank=False, unique=True)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)

class Transaction(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    paid_amount = models.FloatField()
    timestamp = models.DateField(default=timezone.now)
    
 

shop/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.validators import URLValidator, ValidationError
from django.db import IntegrityError 
from hashlib import md5


from django.contrib.auth.models import User, Group
from shop.models import Game, Developer, Player, Transaction
# Create your views here.
def index(request):
    if request.method == "GET":
        user = request.user
        if not request.user.is_authenticated:
            return redirect("shop:home")
        if user.groups.filter(name="developers").count() != 0:
            return redirect("shop:developer")
        transactions = Transaction.objects.filter(player=user.player.id)
        purchased_games = []
        for transaction in transactions:
            purchased_games.append(transaction.game)
        return render(request, "shop/index.html", {"user":user, "purchased_games":purchased_games})

def signup(request):
    if request.user.is_authenticated:
        return redirect("shop:index")
    return render(request, 'shop/signup.html')


def logout_view(request):
    logout(request)
    return redirect("shop:login")


def login_view(request):
    if request.user.is_authenticated:
        return redirect("shop:index")
    return render(request, 'shop/login.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        if not username or not password:
            return render(request, "shop/login.html", {"error":"One of the fields was empty"})
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("shop:index")
        else:
            return render(request, "shop/login.html", {"error":"Wrong username or password"})
    else:
        return redirect("shop:index")


def home(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect("shop:index")
        games = Game.objects.all()
        return render(request, "shop/home.html", {"games":games})
    else:
        return HttpResponse(status=500)

def create(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        developer = False
        try:
            if request.POST['developer']:
                developer = True
        except KeyError:
            developer = False
        if username is not None and email is not None and password is not None:
            if not username or not email or not password:
                return render(request, "shop/signup.html", {"error": "Please fill in all required fields"})
            if User.objects.filter(username=username).exists():
                return render(request, "shop/signup.html", {"error": "Username already exists"})
            elif User.objects.filter(email=email).exists():
                return render(request, "shop/signup.html", {"error": "Email already exists"})
            user = User.objects.create_user(username, email, password)
            if developer:
                if Group.objects.filter(name="developers").exists():
                    dev_group = Group.objects.get(name="developers")
                else:
                    Group.objects.create(name='developers').save()
                    dev_group = Group.objects.get(name='developers')
                dev_group.user_set.add(user)
                Developer.objects.create(user=user).save()
            else:
                Player.objects.create(user=user).save()
            user.save()
            login(request, user, backend="django.contrib.auth.backends.ModelBackend")
        return redirect("shop:index")


    else:
        return redirect("shop:signup")

def catalog_view(request):
    if request.method == 'GET':
        user  = request.user

        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            return redirect('shop:index')

        games = Game.objects.all()
        return render(request, 'shop/catalog.html', {'games':games})

    else:
        return HttpResponse(status=500)


def play_game(request, game_id):
    if request.method == 'GET':
        user  = request.user
        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            return redirect('shop:index')

        game = get_object_or_404(Game, pk=game_id)
        player = user.player
        transaction = Transaction.objects.filter(game=game_id, player=player.id)

        if transaction.count() !=0 :
            return render(request , 'shop/play_game.html', {'game':game})
        else:
            return HttpResponse(status=500)

    else:
        return HttpResponse(status=500)
        

def game_info(request, game_id):
    
    if request.method == 'GET':
        user  = request.user
        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            return redirect('shop:index')
        game        = get_object_or_404(Game, pk=game_id)
        secret_key  = 'f8844b48591841836b4e42d26fcf755c'
        pid         = 'coastseller'
        sid         = 'myshopapp'
        amount      =  game.price
        success     = 'https://mygameshop.herokuapp.com/payment/success/?game_id={}'.format(game_id)
        cancel      = 'https://mygameshop.herokuapp.com/payment/cancel'
        error       = 'https://mygameshop.herokuapp.com/payment/error'
        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        digest      = md5(checksumstr.encode('ascii')) 
        checksum    = digest.hexdigest()
        url         = 'http://payments.webcourse.niksula.hut.fi/pay/'
        transaction = Transaction.objects.filter(player=user.player.id, game=game.id)

        if transaction.count() !=0:
            return render(request, "shop/index.html", {"error": "Game is already in catalog"})
        else:
            return render(request, 'shop/game_info.html', {'game':game,'url':url,'pid':pid,
                                                            'sid':sid,'amount':amount,'success':success,
                                                            'cancel':cancel,'error':error,'checksum':checksum})

    else:
        return HttpResponse(status=500)
            


        

def payment_success(request):
    if request.method == 'GET':
        user  = request.user
        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            return redirect('shop:index')
        
        game_id = request.GET['game_id']
        game   = get_object_or_404(Game, pk=game_id)
        secret_key = 'f8844b48591841836b4e42d26fcf755c'
        pid      =  request.GET['pid']
        ref      =  request.GET['ref']
        result   =  request.GET['result']
        checksum =  request.GET['checksum']

        checksumstr = "pid={}&ref={}&result={}&token={}".format(pid, ref, result, secret_key)
        digest      = md5(checksumstr.encode('ascii')) 
        calculated_hash = digest.hexdigest()

        if calculated_hash == checksum:
            Transaction.objects.create(game=game,player=user.player, paid_amount=game.price).save()
            return redirect('shop:index')
        else:
            return HttpResponse(status=500)
    
    else:
        return HttpResponse(status=500)


def payment_cancel(request):
    if request.method == 'GET':
        user  = request.user
        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            return redirect('shop:index')
        
        secret_key = 'f8844b48591841836b4e42d26fcf755c'
        pid      =  request.GET['pid']
        ref      =  request.GET['ref']
        result   =  request.GET['result']
        checksum =  request.GET['checksum']

        checksumstr = "pid={}&ref={}&result={}&token={}".format(pid, ref, result, secret_key)
        digest      = md5(checksumstr.encode('ascii')) 
        calculated_hash = digest.hexdigest()

        if calculated_hash == checksum:
            return render(request, 'shop/index.html', {'error':'Payment is cancelled'})
        else:
            return HttpResponse(status=500)
    
    else:
        return HttpResponse(status=500)


def payment_error(request):
    pass
 

def developer_view(request):
    if request.method == 'GET':
        user = request.user
        if not user.is_authenticated:
            return redirect('shop:login')
        if user.groups.filter(name='developers').count() !=0:
            games  = Game.objects.filter(developer=user.developer.id)
            statistics  = []

            for game in games:
                transactions  = Transaction.objects.filter(game=game.id)
                for transaction in transactions:
                    statistics.append(transaction)
            return render(request, 'shop/developer.html', {'statistics':statistics})

        else:
            return redirect('shop:index')

    return HttpResponse(status=500)

def search(request):
    if request.method == 'POST':
        user = request.user
        if not user.is_authenticated:
            return HttpResponse(status=500)
        if user.groups.filter(name='developers').count() !=0:
            return HttpResponse(status=500)
        query = request.POST['q']

        if not query:
            return render(request, 'shop/search_result.html', {'error':'0 items returned'})
        games = Game.objects.filter(title__icontains=query)

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gameshop</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/bulma-0.6.2/css/bulma.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/main.css' %}"/>
</head>
<body>
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'shop:index' %}">
            <img src="{% static 'shop/images/face-with-stuck-out-tongue-emoji-emoticon-vector-icon.png' %}" alt="Bulma: a modern CSS framework based on Flexbox"
                 width="40" height="40">
        </a>
    </div>

    <div class="navbar-end">

        <div class="navbar-item">
          {% if request.path == "/login" %}
            <a href="{% url 'shop:signup' %}" class="button">Signup</a>
            {% elif request.path == "/signup"  %}
            <a href="{% url 'shop:login' %}" class="button">Login</a>
            {% elif request.path == "/home"  %}
            <a href="{% url 'shop:login' %}" class="button">Login</a>
        {% endif %}
        </div>
    </div>
</nav>
<section class="section">
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</section>

</body>
</html>

shop/templates/shop/developer.html
{% extends "shop/developer_base.html" %}
{% block content %}


    <div class="columns">
        <div class="column">
            <div class="tile is-ancestor has-text-centered">
                <div style="margin: auto;" class="tile is-parent">
                    <div class="tile is-child box">
                        <h1 class="title is-2"> Hello Developer, &nbsp<span
                                style="color:#1496ed">{{ user.username }}</span></h1>



                        <h2 class="title is-3">Welcome to the game shop.</h2>
                        <h4 class="title is-4">This is your home page.</h4>
                        <h4 class="title is-5">You can publish new games here:</h4>
                        <a class="button is-info is-medium" href="{% url 'shop:publish' %}">Publish new game</a>
                    </div>
                </div>
            </div>

                <h2 class="title " style="color:#00d1b2">Purchasing statistics:</h2>
                    {% for transaction in statistics %}
                        <div class="box">
                            <div class="content">
                                <p class="title is-medium">{{ transaction.game.title }}</p>
                                <p class="subtitle is-small">Buyer: {{ transaction.player.user }}</p>
                                <p class="subtitle is-small">Time: {{ transaction.timestamp }}</p>
                                <p class="subtitle is-small">Paid: {{ transaction.game.price }}€</p>
                            </div>
                        </div>
                    {% endfor %}
        </div>
    </div>


{% endblock content %}

shop/templates/shop/developer_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gameshop</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/bulma-0.6.2/css/bulma.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/catalog.css' %}"/>
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'shop:index' %}">
            <img src="{% static 'shop/images/face-with-stuck-out-tongue-emoji-emoticon-vector-icon.png' %}"
                 alt="Bulma: a modern CSS framework based on Flexbox"
                 width="40" height="40">
        </a>
        <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>

     <div class="navbar-end">
         <div class="navbar-item">
             <div id="navMenu" class="navbar-menu">
                <div class="navbar" style="min-height: 1.25rem;">
                    <div class="navbar-item has-dropdown is-hoverable is-mobile">
                        <a class="navbar-link">
                            Menu
                        </a>
                        <div class="navbar-dropdown is-boxed">
                            <a class="navbar-item" href="{% url 'shop:developer_games' %}">Inventory</a>
                             <a class="navbar-item" href="{% url 'shop:publish' %}">Publish</a>
                            <a class="navbar-item" href="{% url 'shop:logout' %}">Logout</a>
                        </div>
                    </div>
                </div>
            </div>
         </div>
          <div class="navbar-item">

         </div>
     </div>
</nav>

<section class="section">
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</section>


<script src="{% static 'shop/js/burger.js' %}"></script>
</body>
</html>

shop/templates/shop/developer_games.html
{% extends "shop/developer_base.html" %}
{% block content %}


    <div class="columns">
        <div class="column">
            <h2 class="title is-2">Games developed by: <span style="color:blue">{{ user.username }}</span></h2>
            {% for game in games %}
                <div class="box">
                    <div class="content">
                        <p class="title is-medium">{{ game.title }}</p>
                        <p class="subtitle is-small">Built by {{ game.developer }}</p>
                        <a class="button is-primary is-medium" href="{% url 'shop:editgame' game.id %}">Edit</a>
                        <div class="title is-pulled-right">{{ game.price }}$</div>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>

{% endblock content %}

shop/templates/shop/edit_game.html
{% extends "shop/developer_base.html" %}
{% block content %}


    <div class="columns">
          <div class="column is-one-fifth">

          </div>

        <div class="column" >
                {% if error %}
                    <h3 style="color: red">{{ error }}</h3>
                {% endif %}

            <h4 class="title is-5"> You can update all or one of the fields.</h4>

            <form action="{% url 'shop:updategame' game.id %}" method="post">
            {% csrf_token %}
                <div class="field">
                  <div class="control">
                    <label class="label">Game title</label>
                    <input class="input is-primary" placeholder="" value="{{ game.title }}" type="text" name="title">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <label class="label">Price</label>
                    <input class="input is-primary" value="{{ game.price }}" type="number" name="price">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                      <label class="label">Game URL</label>
                    <input class="input is-primary" value="{{ game.url }}" type="text" name="url">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <button class="button is-success is-outlined is-fullwidth" type="submit" value="Update">Update</button>&nbsp;
                  </div>
                </div>
            </form>

            <h3 class="title is-5">Delete Game {{ game.title }}</h3>
            <form action="{% url 'shop:deletegame' game.id %}" method="post">
                {% csrf_token %}
                 <button class="button is-danger is-outlined is-fullwidth" type="submit" name="delete" value="Delete">Delete</button>&nbsp;

            </form>
         </div>
        <div class="column ">

          </div>

    </div>


{% endblock content %}

shop/templates/shop/home.html
{% extends "shop/base.html" %}
{% block content %}
    <h1 class="title">
        The world of gamers is here!
    </h1>

    {% for game in games %}
                <div class="box">
                    <div class="content">
                        <p class="title is-medium">{{ game.title }}</p>
                        <p class="subtitle is-small">Built by {{ game.developer }}</p>
                        <div class="title is-pulled-right">{{ game.price }}$</div>
                    </div>
                </div>
            {% endfor %}



{% endblock content %}   

shop/templates/shop/index.html
{% extends "shop/player_base.html" %}
{% block content %}
    {% if error %}
        <h3 style="color: red">{{ error }}</h3>
    {% endif %}


         <div class="has-text-centered tile is-ancestor">
           <div style="margin: auto" class="tile is-8 is-parent">
               <div class="tile is-child box">
                   <h1 class="title is-2"> Hello, &nbsp;<span style="color:
                                   #1496ed">{{ user.username }}</span> </h1>




            <h2 class="title is-3">Welcome to the game shop.</h2>
            <h4 class="title is-4">This is your home page.</h4>
            <h4 class="title is-5">You can access to different features of the website by clicking the navbar.</h4>
            <h4 class="title is-5" style="color:#1496ed">You can also see your games here:</h4>
    </div>
  </div>
    </div>

<div style="margin: auto" class="has-text-centered column is-half-desktop">
         {% for game in purchased_games %}
                <div class="box">
                    <div class="content">
                        <p class="title is-medium">{{ game.title }}</p>
                        <a class="button is-success is-medium" href="{% url 'shop:play_game' game.id %}">Play</a>
                    </div>
                </div>
            {% endfor %}
</div>




{% endblock content %}

shop/templates/shop/login.html
{% extends "shop/base.html" %}

{% block content %}

<div class="columns">
      <div class="column">
          <div  style="margin-left:20px; color:red">
                     {% if error %}
                      <h2>{{ error }}</h2>
                   {% endif %}
                </div>
           <nav class="panel">
            <p class="panel-heading" style="text-align:center">
            <span><strong>Login</strong></span>
            </p>

            <div class="panel-block">
                 <form action="{% url 'shop:loguser' %}" method="post">
                      {% csrf_token %}
                      <div class="field">
                          <label class="label">Username</label>
                            <div class="control has-icons-left has-icons-right">
                              <input class="input is-success" type="text" placeholder="Username" name="username">
                              <span class="icon is-small is-left">
                                <i class="fas fa-user"></i>
                              </span>
                              <span class="icon is-small is-right">
                                <i class="fas fa-check"></i>
                              </span>
                            </div>
                      </div>

                      <div class="field">
                          <label class="label">Password</label>
                          <div class="control has-icons-left">
                              <input class="input" name="password" placeholder="Password" type="password">
                              <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                              </span>
                          </div>

                      </div>
                      <div class="field">
                          <div class="control">
                              <button class="button is-success is-outlined is-fullwidth" type="submit" value="Login">Login</button>&nbsp;

                           </div>
                      </div>

                      <div class="panel-block">
                                        <a class="button is-link is-outlined is-fullwidth" onclick="$(this).button('loading');" style="background:blue; color:white" name="facebook" href="{% url 'social:begin' 'facebook' %}">
                                             Login with  Facebook
                                        </a>

                      </div>

                  </form>
            </div>
          </nav>

        </div>
      </div>


{% endblock content %}

shop/templates/shop/play_game.html
{% extends "shop/player_base.html" %}
{% block content %}


<h1 id="game_title" class="title">Play the game {{ game.title }} in the iFrame</h1>
<iframe class="box" id="game_frame" width="500" height="400" src="{{ game.url }}"></iframe>
{% endblock content %}

shop/templates/shop/player_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gameshop</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/bulma-0.6.2/css/bulma.css' %}"/>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    {#    <link rel="stylesheet" type="text/css" href="{% static 'shop/main.css' %}"/>#}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/catalog.css' %}"/>
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'shop:index' %}">
            <img src="{% static 'shop/images/face-with-stuck-out-tongue-emoji-emoticon-vector-icon.png' %}"
                 alt="Bulma: a modern CSS framework based on Flexbox"
                 width="40" height="40">
        </a>
        <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div class="navbar-end">
        <div class="navbar-item">
            <form action="{% url 'shop:search' %}" method="post">
                {% csrf_token %}
                <p class="control has-icons-left">
                    <input class="input" type="text" name="q" placeholder="search">
                    <span class="icon is-left">
                <i class="fas fa-search"></i>
              </span>
                </p>
            </form>

        </div>
        <div class="navbar-item">
            <div id="navMenu" class="navbar-menu">
                <div class="navbar" style="min-height: 1.25rem;">
                    <div class="navbar-item has-dropdown is-hoverable is-mobile">
                        <a class="navbar-link">
                            Menu
                        </a>
                        <div class="navbar-dropdown is-boxed">
                            <a class="navbar-item" href="{% url 'shop:catalog' %}">
                                Catalog
                            </a>
                            <a class="navbar-item" href="{% url 'shop:logout' %}">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-item">

        </div>

    </div>

</nav>
<section class="section">
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</section>


<script src="{% static 'shop/js/burger.js' %}"></script>
</body>
</html>

shop/templates/shop/publish_game_form.html
{% extends "shop/developer_base.html" %}
{% block content %}


    <div class="publish-form columns">

        <div class="column" >
            <h4 class="title is-5">Input Detail information about the game:</h4>
             {% if error %}
                    <h3 style="color: red">{{ error }}</h3>
                {% endif %}
            <form action="{% url 'shop:publish_game' %}" method="post">
            {% csrf_token %}
                <div class="field">
                  <div class="control">
                    <label class="label">Game title</label>
                    <input class="input is-primary" placeholder="Title" type="text" name="title">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <label class="label">Price</label>
                    <input class="input is-primary" placeholder="Price" type="number" name="price">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                      <label class="label">Game URL</label>
                    <input class="input is-primary" placeholder="URL" type="text" name="url">
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <button class="button is-success is-outlined is-fullwidth" type="submit" value="Publish">Publish</button>&nbsp;
                  </div>
                </div>

            </form>
         </div>
    </div>


{% endblock content %}

shop/templates/shop/search_result.html
{% extends "shop/player_base.html" %}
{% block content %}

    {% if error %}
        <h3 style="color: red">{{ error }}</h3>

    {% endif %}
    <div class="columns">
        <div class="column">
            <h1 style="color: #0f81cc" class="title">Search results for {{query}}</h1>
            {% for game in games %}
                <div class="box">
                    <div class="content">
                        <p class="title is-medium">{{ game.title }}</p>
                        <p class="subtitle is-small">Built by {{ game.developer }}</p>
                        <a class="button is-info is-medium" href="{% url 'shop:game_info' game.id %}">Add to cart</a>
                        <div class="title is-pulled-right">{{ game.price }}$</div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>


{% endblock content %}